-- H2 2.3.232;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT 'f76ff208074272e9' HASH 'd914186c84eff13e15d1098196988a184f72d9e264eefd75f36b891ad78b9f8c' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."ATTENDANCE"(
    "ID" UUID NOT NULL,
    "CHECKIN_TIME" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "REGISTRATION_ID" UUID NOT NULL
);        
ALTER TABLE "PUBLIC"."ATTENDANCE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ATTENDANCE;              
CREATE MEMORY TABLE "PUBLIC"."COLLEGES"(
    "ID" UUID NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL
);             
ALTER TABLE "PUBLIC"."COLLEGES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8F" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COLLEGES;
CREATE MEMORY TABLE "PUBLIC"."EVENTS"(
    "ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "END_TIME" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "LOCATION" CHARACTER VARYING(255),
    "START_TIME" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "TITLE" CHARACTER VARYING(255) NOT NULL,
    "TYPE" ENUM('Fest', 'Hackathon', 'Seminar', 'TechTalk', 'Workshop') NOT NULL,
    "COLLEGE_ID" UUID NOT NULL
); 
ALTER TABLE "PUBLIC"."EVENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EVENTS;  
CREATE MEMORY TABLE "PUBLIC"."FEEDBACK"(
    "ID" UUID NOT NULL,
    "COMMENTS" CHARACTER VARYING(255),
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "RATING" INTEGER NOT NULL,
    "REGISTRATION_ID" UUID NOT NULL
);    
ALTER TABLE "PUBLIC"."FEEDBACK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FEEDBACK;
CREATE MEMORY TABLE "PUBLIC"."REGISTRATIONS"(
    "ID" UUID NOT NULL,
    "REGISTERED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "EVENT_ID" UUID NOT NULL,
    "STUDENT_ID" UUID NOT NULL
);          
ALTER TABLE "PUBLIC"."REGISTRATIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REGISTRATIONS;           
CREATE MEMORY TABLE "PUBLIC"."STUDENTS"(
    "ID" UUID NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "COLLEGE_ID" UUID NOT NULL
);              
ALTER TABLE "PUBLIC"."STUDENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.STUDENTS;
ALTER TABLE "PUBLIC"."STUDENTS" ADD CONSTRAINT "PUBLIC"."UKDGPKR8JN6XRWOCPS315B9YJU5" UNIQUE NULLS DISTINCT ("COLLEGE_ID", "EMAIL");          
ALTER TABLE "PUBLIC"."ATTENDANCE" ADD CONSTRAINT "PUBLIC"."UK1W4KW24VPS52YRAB1WS88FW1E" UNIQUE NULLS DISTINCT ("REGISTRATION_ID");            
ALTER TABLE "PUBLIC"."REGISTRATIONS" ADD CONSTRAINT "PUBLIC"."UK7MQE6G11PUPQPU0CW6COKBRA9" UNIQUE NULLS DISTINCT ("STUDENT_ID", "EVENT_ID");  
ALTER TABLE "PUBLIC"."COLLEGES" ADD CONSTRAINT "PUBLIC"."UK4Q2VSGB93D2WYBLODEJ8R5HMC" UNIQUE NULLS DISTINCT ("NAME");         
ALTER TABLE "PUBLIC"."FEEDBACK" ADD CONSTRAINT "PUBLIC"."UKFYX9014EWXEDIHB5BEQT7TTWW" UNIQUE NULLS DISTINCT ("REGISTRATION_ID");              
ALTER TABLE "PUBLIC"."FEEDBACK" ADD CONSTRAINT "PUBLIC"."FKKJLI3BAQHIOB0CK09RXMT94BP" FOREIGN KEY("REGISTRATION_ID") REFERENCES "PUBLIC"."REGISTRATIONS"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."EVENTS" ADD CONSTRAINT "PUBLIC"."FK3G7EQY9H9KOV3ICBUMNQMJSJ3" FOREIGN KEY("COLLEGE_ID") REFERENCES "PUBLIC"."COLLEGES"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."REGISTRATIONS" ADD CONSTRAINT "PUBLIC"."FK8MI58JT1S8FXMI56JNAU0CXQW" FOREIGN KEY("EVENT_ID") REFERENCES "PUBLIC"."EVENTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."ATTENDANCE" ADD CONSTRAINT "PUBLIC"."FKMLK88RQDY5JYF5CKXMMPM00VF" FOREIGN KEY("REGISTRATION_ID") REFERENCES "PUBLIC"."REGISTRATIONS"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."STUDENTS" ADD CONSTRAINT "PUBLIC"."FK5M8JBC0PRE8WG5U8WFGYLNFV7" FOREIGN KEY("COLLEGE_ID") REFERENCES "PUBLIC"."COLLEGES"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."REGISTRATIONS" ADD CONSTRAINT "PUBLIC"."FKCMO9LK1TAP4HPBAWUXHB8QF94" FOREIGN KEY("STUDENT_ID") REFERENCES "PUBLIC"."STUDENTS"("ID") NOCHECK;            
